# yaml-language-server: $schema=https://raw.githubusercontent.com/dbt-labs/dbt-jobs-as-code/main/src/dbt_jobs_as_code/schemas/load_job_schema.json

jobs:
  job1:
    account_id: {{ account_id }}
    project_id: {{ project_id }}
    environment_id: {{ environment_id }}
    dbt_version: null
    deferring_job_definition_id: null
    execute_steps:
    - "dbt run"
    execution:
      timeout_seconds: 0
    generate_docs: false
    name: "dbt_run"
    run_generate_sources: true
    schedule:
      cron: "0 */2 * * *"
    settings:
      target_name: production
      threads: 4
    state: 1
    triggers:
      git_provider_webhook: false
      github_webhook: false
      schedule: true

  job2:
    account_id: {{ account_id }}
    project_id: {{ project_id }}
    environment_id: {{ environment_id }}
    dbt_version: null
    deferring_job_definition_id: null
    execute_steps:
    - dbt compile
    execution:
      timeout_seconds: 0
    generate_docs: false
    name: dbt_compile
    run_generate_sources: false
    schedule:
      cron: "0 * * * *"
    settings:
      target_name: production
      threads: 4
    state: 1
    triggers:
      git_provider_webhook: false
      github_webhook: false
      schedule: true
